// Code generated by gocc; DO NOT EDIT.

package lexer

import (
	"io/ioutil"
	"unicode/utf8"

	"github.com/day-dreams/TrivialCompiler/token"
)

const (
	NoState    = -1
	NumStates  = 63
	NumSymbols = 72
)

type Lexer struct {
	src    []byte
	pos    int
	line   int
	column int
}

func NewLexer(src []byte) *Lexer {
	lexer := &Lexer{
		src:    src,
		pos:    0,
		line:   1,
		column: 1,
	}
	return lexer
}

func NewLexerFile(fpath string) (*Lexer, error) {
	src, err := ioutil.ReadFile(fpath)
	if err != nil {
		return nil, err
	}
	return NewLexer(src), nil
}

func (l *Lexer) Scan() (tok *token.Token) {
	tok = new(token.Token)
	if l.pos >= len(l.src) {
		tok.Type = token.EOF
		tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = l.pos, l.line, l.column
		return
	}
	start, startLine, startColumn, end := l.pos, l.line, l.column, 0
	tok.Type = token.INVALID
	state, rune1, size := 0, rune(-1), 0
	for state != -1 {
		if l.pos >= len(l.src) {
			rune1 = -1
		} else {
			rune1, size = utf8.DecodeRune(l.src[l.pos:])
			l.pos += size
		}

		nextState := -1
		if rune1 != -1 {
			nextState = TransTab[state](rune1)
		}
		state = nextState

		if state != -1 {

			switch rune1 {
			case '\n':
				l.line++
				l.column = 1
			case '\r':
				l.column = 1
			case '\t':
				l.column += 4
			default:
				l.column++
			}

			switch {
			case ActTab[state].Accept != -1:
				tok.Type = ActTab[state].Accept
				end = l.pos
			case ActTab[state].Ignore != "":
				start, startLine, startColumn = l.pos, l.line, l.column
				state = 0
				if start >= len(l.src) {
					tok.Type = token.EOF
				}

			}
		} else {
			if tok.Type == token.INVALID {
				end = l.pos
			}
		}
	}
	if end > start {
		l.pos = end
		tok.Lit = l.src[start:end]
	} else {
		tok.Lit = []byte{}
	}
	tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = start, startLine, startColumn

	return
}

func (l *Lexer) Reset() {
	l.pos = 0
}

/*
Lexer symbols:
0: '0'
1: '+'
2: '-'
3: '*'
4: '/'
5: '('
6: ')'
7: ';'
8: '{'
9: '}'
10: '"'
11: 'C'
12: 'o'
13: 'd'
14: 'e'
15: 'G'
16: 'e'
17: 'n'
18: 'G'
19: 'o'
20: 'S'
21: 't'
22: 'r'
23: 'u'
24: 'c'
25: 't'
26: 't'
27: 'y'
28: 'p'
29: 'e'
30: 's'
31: 't'
32: 'r'
33: 'u'
34: 'c'
35: 't'
36: 's'
37: 't'
38: 'r'
39: 'i'
40: 'n'
41: 'g'
42: 'i'
43: 'n'
44: 't'
45: 'i'
46: 'n'
47: 't'
48: '6'
49: '4'
50: 'b'
51: 'o'
52: 'o'
53: 'l'
54: 'f'
55: 'l'
56: 'o'
57: 'a'
58: 't'
59: '6'
60: '4'
61: '`'
62: '_'
63: '\t'
64: '\n'
65: '\r'
66: ' '
67: '1'-'9'
68: 'A'-'Z'
69: 'a'-'z'
70: '0'-'9'
71: .
*/
