/* Lexical Part */

id : 'a'-'z' {'a'-'z'} ;

!whitespace : ' ' | '\t' | '\n' | '\r' ;

/* Syntax Part */

<< import "github.com/day-dreams/TrivialCompiler/ast" >>

Hello:  "hello" id << ast.NewWorld($1) >> ;