// Code generated by gocc; DO NOT EDIT.

package parser

type (
	actionTable [numStates]actionRow
	actionRow   struct {
		canRecover bool
		actions    [numSymbols]action
	}
)

var actionTab = actionTable{
	actionRow{ // S0
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(17), // $, reduce: Statements
			shift(5),   // cmdcodegengostruct
			nil,        // gotypeof
			nil,        // ident
			nil,        // gostructdef
			nil,        // lbrace
			nil,        // rbrace
			nil,        // empty
			nil,        // gostring
			nil,        // goint
			nil,        // goint64
			nil,        // gobool
			nil,        // gofloat64
			nil,        // gotag
			nil,        // semicolon
			nil,        // plus
			nil,        // minus
			nil,        // mul
			nil,        // div
			reduce(17), // lparen, reduce: Statements
			nil,        // rparen
			reduce(17), // int, reduce: Statements
		},
	},
	actionRow{ // S1
		canRecover: false,
		actions: [numSymbols]action{
			nil,          // INVALID
			accept(true), // $
			nil,          // cmdcodegengostruct
			nil,          // gotypeof
			nil,          // ident
			nil,          // gostructdef
			nil,          // lbrace
			nil,          // rbrace
			nil,          // empty
			nil,          // gostring
			nil,          // goint
			nil,          // goint64
			nil,          // gobool
			nil,          // gofloat64
			nil,          // gotag
			nil,          // semicolon
			nil,          // plus
			nil,          // minus
			nil,          // mul
			nil,          // div
			nil,          // lparen
			nil,          // rparen
			nil,          // int
		},
	},
	actionRow{ // S2
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(1), // $, reduce: Program
			nil,       // cmdcodegengostruct
			nil,       // gotypeof
			nil,       // ident
			nil,       // gostructdef
			nil,       // lbrace
			nil,       // rbrace
			nil,       // empty
			nil,       // gostring
			nil,       // goint
			nil,       // goint64
			nil,       // gobool
			nil,       // gofloat64
			nil,       // gotag
			nil,       // semicolon
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // div
			shift(10), // lparen
			nil,       // rparen
			shift(11), // int
		},
	},
	actionRow{ // S3
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(2), // $, reduce: Program
			nil,       // cmdcodegengostruct
			nil,       // gotypeof
			nil,       // ident
			nil,       // gostructdef
			nil,       // lbrace
			nil,       // rbrace
			nil,       // empty
			nil,       // gostring
			nil,       // goint
			nil,       // goint64
			nil,       // gobool
			nil,       // gofloat64
			nil,       // gotag
			nil,       // semicolon
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // div
			nil,       // lparen
			nil,       // rparen
			nil,       // int
		},
	},
	actionRow{ // S4
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // cmdcodegengostruct
			shift(13), // gotypeof
			nil,       // ident
			nil,       // gostructdef
			nil,       // lbrace
			nil,       // rbrace
			nil,       // empty
			nil,       // gostring
			nil,       // goint
			nil,       // goint64
			nil,       // gobool
			nil,       // gofloat64
			nil,       // gotag
			nil,       // semicolon
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // div
			nil,       // lparen
			nil,       // rparen
			nil,       // int
		},
	},
	actionRow{ // S5
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // cmdcodegengostruct
			reduce(4), // gotypeof, reduce: Cmd
			nil,       // ident
			nil,       // gostructdef
			nil,       // lbrace
			nil,       // rbrace
			nil,       // empty
			nil,       // gostring
			nil,       // goint
			nil,       // goint64
			nil,       // gobool
			nil,       // gofloat64
			nil,       // gotag
			nil,       // semicolon
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // div
			nil,       // lparen
			nil,       // rparen
			nil,       // int
		},
	},
	actionRow{ // S6
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(16), // $, reduce: Statements
			nil,        // cmdcodegengostruct
			nil,        // gotypeof
			nil,        // ident
			nil,        // gostructdef
			nil,        // lbrace
			nil,        // rbrace
			nil,        // empty
			nil,        // gostring
			nil,        // goint
			nil,        // goint64
			nil,        // gobool
			nil,        // gofloat64
			nil,        // gotag
			nil,        // semicolon
			nil,        // plus
			nil,        // minus
			nil,        // mul
			nil,        // div
			reduce(16), // lparen, reduce: Statements
			nil,        // rparen
			reduce(16), // int, reduce: Statements
		},
	},
	actionRow{ // S7
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // cmdcodegengostruct
			nil,       // gotypeof
			nil,       // ident
			nil,       // gostructdef
			nil,       // lbrace
			nil,       // rbrace
			nil,       // empty
			nil,       // gostring
			nil,       // goint
			nil,       // goint64
			nil,       // gobool
			nil,       // gofloat64
			nil,       // gotag
			shift(14), // semicolon
			shift(16), // plus
			shift(17), // minus
			nil,       // mul
			nil,       // div
			nil,       // lparen
			nil,       // rparen
			nil,       // int
		},
	},
	actionRow{ // S8
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // cmdcodegengostruct
			nil,        // gotypeof
			nil,        // ident
			nil,        // gostructdef
			nil,        // lbrace
			nil,        // rbrace
			nil,        // empty
			nil,        // gostring
			nil,        // goint
			nil,        // goint64
			nil,        // gobool
			nil,        // gofloat64
			nil,        // gotag
			reduce(20), // semicolon, reduce: Expression
			reduce(20), // plus, reduce: Expression
			reduce(20), // minus, reduce: Expression
			shift(18),  // mul
			shift(19),  // div
			nil,        // lparen
			nil,        // rparen
			nil,        // int
		},
	},
	actionRow{ // S9
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // cmdcodegengostruct
			nil,        // gotypeof
			nil,        // ident
			nil,        // gostructdef
			nil,        // lbrace
			nil,        // rbrace
			nil,        // empty
			nil,        // gostring
			nil,        // goint
			nil,        // goint64
			nil,        // gobool
			nil,        // gofloat64
			nil,        // gotag
			reduce(25), // semicolon, reduce: Term
			reduce(25), // plus, reduce: Term
			reduce(25), // minus, reduce: Term
			reduce(25), // mul, reduce: Term
			reduce(25), // div, reduce: Term
			nil,        // lparen
			nil,        // rparen
			nil,        // int
		},
	},
	actionRow{ // S10
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // cmdcodegengostruct
			nil,       // gotypeof
			nil,       // ident
			nil,       // gostructdef
			nil,       // lbrace
			nil,       // rbrace
			nil,       // empty
			nil,       // gostring
			nil,       // goint
			nil,       // goint64
			nil,       // gobool
			nil,       // gofloat64
			nil,       // gotag
			nil,       // semicolon
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // div
			shift(23), // lparen
			nil,       // rparen
			shift(24), // int
		},
	},
	actionRow{ // S11
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // cmdcodegengostruct
			nil,        // gotypeof
			nil,        // ident
			nil,        // gostructdef
			nil,        // lbrace
			nil,        // rbrace
			nil,        // empty
			nil,        // gostring
			nil,        // goint
			nil,        // goint64
			nil,        // gobool
			nil,        // gofloat64
			nil,        // gotag
			reduce(27), // semicolon, reduce: Factor
			reduce(27), // plus, reduce: Factor
			reduce(27), // minus, reduce: Factor
			reduce(27), // mul, reduce: Factor
			reduce(27), // div, reduce: Factor
			nil,        // lparen
			nil,        // rparen
			nil,        // int
		},
	},
	actionRow{ // S12
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(3), // $, reduce: Command
			nil,       // cmdcodegengostruct
			nil,       // gotypeof
			nil,       // ident
			nil,       // gostructdef
			nil,       // lbrace
			nil,       // rbrace
			nil,       // empty
			nil,       // gostring
			nil,       // goint
			nil,       // goint64
			nil,       // gobool
			nil,       // gofloat64
			nil,       // gotag
			nil,       // semicolon
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // div
			nil,       // lparen
			nil,       // rparen
			nil,       // int
		},
	},
	actionRow{ // S13
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // cmdcodegengostruct
			nil,       // gotypeof
			shift(25), // ident
			nil,       // gostructdef
			nil,       // lbrace
			nil,       // rbrace
			nil,       // empty
			nil,       // gostring
			nil,       // goint
			nil,       // goint64
			nil,       // gobool
			nil,       // gofloat64
			nil,       // gotag
			nil,       // semicolon
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // div
			nil,       // lparen
			nil,       // rparen
			nil,       // int
		},
	},
	actionRow{ // S14
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(18), // $, reduce: Statement
			nil,        // cmdcodegengostruct
			nil,        // gotypeof
			nil,        // ident
			nil,        // gostructdef
			nil,        // lbrace
			nil,        // rbrace
			nil,        // empty
			nil,        // gostring
			nil,        // goint
			nil,        // goint64
			nil,        // gobool
			nil,        // gofloat64
			nil,        // gotag
			nil,        // semicolon
			nil,        // plus
			nil,        // minus
			nil,        // mul
			nil,        // div
			reduce(18), // lparen, reduce: Statement
			nil,        // rparen
			reduce(18), // int, reduce: Statement
		},
	},
	actionRow{ // S15
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // cmdcodegengostruct
			nil,       // gotypeof
			nil,       // ident
			nil,       // gostructdef
			nil,       // lbrace
			nil,       // rbrace
			nil,       // empty
			nil,       // gostring
			nil,       // goint
			nil,       // goint64
			nil,       // gobool
			nil,       // gofloat64
			nil,       // gotag
			nil,       // semicolon
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // div
			shift(10), // lparen
			nil,       // rparen
			shift(11), // int
		},
	},
	actionRow{ // S16
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // cmdcodegengostruct
			nil,        // gotypeof
			nil,        // ident
			nil,        // gostructdef
			nil,        // lbrace
			nil,        // rbrace
			nil,        // empty
			nil,        // gostring
			nil,        // goint
			nil,        // goint64
			nil,        // gobool
			nil,        // gofloat64
			nil,        // gotag
			nil,        // semicolon
			nil,        // plus
			nil,        // minus
			nil,        // mul
			nil,        // div
			reduce(21), // lparen, reduce: Operation
			nil,        // rparen
			reduce(21), // int, reduce: Operation
		},
	},
	actionRow{ // S17
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // cmdcodegengostruct
			nil,        // gotypeof
			nil,        // ident
			nil,        // gostructdef
			nil,        // lbrace
			nil,        // rbrace
			nil,        // empty
			nil,        // gostring
			nil,        // goint
			nil,        // goint64
			nil,        // gobool
			nil,        // gofloat64
			nil,        // gotag
			nil,        // semicolon
			nil,        // plus
			nil,        // minus
			nil,        // mul
			nil,        // div
			reduce(22), // lparen, reduce: Operation
			nil,        // rparen
			reduce(22), // int, reduce: Operation
		},
	},
	actionRow{ // S18
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // cmdcodegengostruct
			nil,       // gotypeof
			nil,       // ident
			nil,       // gostructdef
			nil,       // lbrace
			nil,       // rbrace
			nil,       // empty
			nil,       // gostring
			nil,       // goint
			nil,       // goint64
			nil,       // gobool
			nil,       // gofloat64
			nil,       // gotag
			nil,       // semicolon
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // div
			shift(10), // lparen
			nil,       // rparen
			shift(11), // int
		},
	},
	actionRow{ // S19
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // cmdcodegengostruct
			nil,       // gotypeof
			nil,       // ident
			nil,       // gostructdef
			nil,       // lbrace
			nil,       // rbrace
			nil,       // empty
			nil,       // gostring
			nil,       // goint
			nil,       // goint64
			nil,       // gobool
			nil,       // gofloat64
			nil,       // gotag
			nil,       // semicolon
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // div
			shift(10), // lparen
			nil,       // rparen
			shift(11), // int
		},
	},
	actionRow{ // S20
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // cmdcodegengostruct
			nil,       // gotypeof
			nil,       // ident
			nil,       // gostructdef
			nil,       // lbrace
			nil,       // rbrace
			nil,       // empty
			nil,       // gostring
			nil,       // goint
			nil,       // goint64
			nil,       // gobool
			nil,       // gofloat64
			nil,       // gotag
			nil,       // semicolon
			shift(16), // plus
			shift(17), // minus
			nil,       // mul
			nil,       // div
			nil,       // lparen
			shift(30), // rparen
			nil,       // int
		},
	},
	actionRow{ // S21
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // cmdcodegengostruct
			nil,        // gotypeof
			nil,        // ident
			nil,        // gostructdef
			nil,        // lbrace
			nil,        // rbrace
			nil,        // empty
			nil,        // gostring
			nil,        // goint
			nil,        // goint64
			nil,        // gobool
			nil,        // gofloat64
			nil,        // gotag
			nil,        // semicolon
			reduce(20), // plus, reduce: Expression
			reduce(20), // minus, reduce: Expression
			shift(31),  // mul
			shift(32),  // div
			nil,        // lparen
			reduce(20), // rparen, reduce: Expression
			nil,        // int
		},
	},
	actionRow{ // S22
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // cmdcodegengostruct
			nil,        // gotypeof
			nil,        // ident
			nil,        // gostructdef
			nil,        // lbrace
			nil,        // rbrace
			nil,        // empty
			nil,        // gostring
			nil,        // goint
			nil,        // goint64
			nil,        // gobool
			nil,        // gofloat64
			nil,        // gotag
			nil,        // semicolon
			reduce(25), // plus, reduce: Term
			reduce(25), // minus, reduce: Term
			reduce(25), // mul, reduce: Term
			reduce(25), // div, reduce: Term
			nil,        // lparen
			reduce(25), // rparen, reduce: Term
			nil,        // int
		},
	},
	actionRow{ // S23
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // cmdcodegengostruct
			nil,       // gotypeof
			nil,       // ident
			nil,       // gostructdef
			nil,       // lbrace
			nil,       // rbrace
			nil,       // empty
			nil,       // gostring
			nil,       // goint
			nil,       // goint64
			nil,       // gobool
			nil,       // gofloat64
			nil,       // gotag
			nil,       // semicolon
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // div
			shift(23), // lparen
			nil,       // rparen
			shift(24), // int
		},
	},
	actionRow{ // S24
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // cmdcodegengostruct
			nil,        // gotypeof
			nil,        // ident
			nil,        // gostructdef
			nil,        // lbrace
			nil,        // rbrace
			nil,        // empty
			nil,        // gostring
			nil,        // goint
			nil,        // goint64
			nil,        // gobool
			nil,        // gofloat64
			nil,        // gotag
			nil,        // semicolon
			reduce(27), // plus, reduce: Factor
			reduce(27), // minus, reduce: Factor
			reduce(27), // mul, reduce: Factor
			reduce(27), // div, reduce: Factor
			nil,        // lparen
			reduce(27), // rparen, reduce: Factor
			nil,        // int
		},
	},
	actionRow{ // S25
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // cmdcodegengostruct
			nil,       // gotypeof
			nil,       // ident
			shift(34), // gostructdef
			nil,       // lbrace
			nil,       // rbrace
			nil,       // empty
			nil,       // gostring
			nil,       // goint
			nil,       // goint64
			nil,       // gobool
			nil,       // gofloat64
			nil,       // gotag
			nil,       // semicolon
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // div
			nil,       // lparen
			nil,       // rparen
			nil,       // int
		},
	},
	actionRow{ // S26
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // cmdcodegengostruct
			nil,        // gotypeof
			nil,        // ident
			nil,        // gostructdef
			nil,        // lbrace
			nil,        // rbrace
			nil,        // empty
			nil,        // gostring
			nil,        // goint
			nil,        // goint64
			nil,        // gobool
			nil,        // gofloat64
			nil,        // gotag
			reduce(19), // semicolon, reduce: Expression
			reduce(19), // plus, reduce: Expression
			reduce(19), // minus, reduce: Expression
			shift(18),  // mul
			shift(19),  // div
			nil,        // lparen
			nil,        // rparen
			nil,        // int
		},
	},
	actionRow{ // S27
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // cmdcodegengostruct
			nil,        // gotypeof
			nil,        // ident
			nil,        // gostructdef
			nil,        // lbrace
			nil,        // rbrace
			nil,        // empty
			nil,        // gostring
			nil,        // goint
			nil,        // goint64
			nil,        // gobool
			nil,        // gofloat64
			nil,        // gotag
			reduce(23), // semicolon, reduce: Term
			reduce(23), // plus, reduce: Term
			reduce(23), // minus, reduce: Term
			reduce(23), // mul, reduce: Term
			reduce(23), // div, reduce: Term
			nil,        // lparen
			nil,        // rparen
			nil,        // int
		},
	},
	actionRow{ // S28
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // cmdcodegengostruct
			nil,        // gotypeof
			nil,        // ident
			nil,        // gostructdef
			nil,        // lbrace
			nil,        // rbrace
			nil,        // empty
			nil,        // gostring
			nil,        // goint
			nil,        // goint64
			nil,        // gobool
			nil,        // gofloat64
			nil,        // gotag
			reduce(24), // semicolon, reduce: Term
			reduce(24), // plus, reduce: Term
			reduce(24), // minus, reduce: Term
			reduce(24), // mul, reduce: Term
			reduce(24), // div, reduce: Term
			nil,        // lparen
			nil,        // rparen
			nil,        // int
		},
	},
	actionRow{ // S29
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // cmdcodegengostruct
			nil,       // gotypeof
			nil,       // ident
			nil,       // gostructdef
			nil,       // lbrace
			nil,       // rbrace
			nil,       // empty
			nil,       // gostring
			nil,       // goint
			nil,       // goint64
			nil,       // gobool
			nil,       // gofloat64
			nil,       // gotag
			nil,       // semicolon
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // div
			shift(23), // lparen
			nil,       // rparen
			shift(24), // int
		},
	},
	actionRow{ // S30
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // cmdcodegengostruct
			nil,        // gotypeof
			nil,        // ident
			nil,        // gostructdef
			nil,        // lbrace
			nil,        // rbrace
			nil,        // empty
			nil,        // gostring
			nil,        // goint
			nil,        // goint64
			nil,        // gobool
			nil,        // gofloat64
			nil,        // gotag
			reduce(26), // semicolon, reduce: Factor
			reduce(26), // plus, reduce: Factor
			reduce(26), // minus, reduce: Factor
			reduce(26), // mul, reduce: Factor
			reduce(26), // div, reduce: Factor
			nil,        // lparen
			nil,        // rparen
			nil,        // int
		},
	},
	actionRow{ // S31
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // cmdcodegengostruct
			nil,       // gotypeof
			nil,       // ident
			nil,       // gostructdef
			nil,       // lbrace
			nil,       // rbrace
			nil,       // empty
			nil,       // gostring
			nil,       // goint
			nil,       // goint64
			nil,       // gobool
			nil,       // gofloat64
			nil,       // gotag
			nil,       // semicolon
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // div
			shift(23), // lparen
			nil,       // rparen
			shift(24), // int
		},
	},
	actionRow{ // S32
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // cmdcodegengostruct
			nil,       // gotypeof
			nil,       // ident
			nil,       // gostructdef
			nil,       // lbrace
			nil,       // rbrace
			nil,       // empty
			nil,       // gostring
			nil,       // goint
			nil,       // goint64
			nil,       // gobool
			nil,       // gofloat64
			nil,       // gotag
			nil,       // semicolon
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // div
			shift(23), // lparen
			nil,       // rparen
			shift(24), // int
		},
	},
	actionRow{ // S33
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // cmdcodegengostruct
			nil,       // gotypeof
			nil,       // ident
			nil,       // gostructdef
			nil,       // lbrace
			nil,       // rbrace
			nil,       // empty
			nil,       // gostring
			nil,       // goint
			nil,       // goint64
			nil,       // gobool
			nil,       // gofloat64
			nil,       // gotag
			nil,       // semicolon
			shift(16), // plus
			shift(17), // minus
			nil,       // mul
			nil,       // div
			nil,       // lparen
			shift(38), // rparen
			nil,       // int
		},
	},
	actionRow{ // S34
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // cmdcodegengostruct
			nil,       // gotypeof
			nil,       // ident
			nil,       // gostructdef
			shift(39), // lbrace
			nil,       // rbrace
			nil,       // empty
			nil,       // gostring
			nil,       // goint
			nil,       // goint64
			nil,       // gobool
			nil,       // gofloat64
			nil,       // gotag
			nil,       // semicolon
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // div
			nil,       // lparen
			nil,       // rparen
			nil,       // int
		},
	},
	actionRow{ // S35
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // cmdcodegengostruct
			nil,        // gotypeof
			nil,        // ident
			nil,        // gostructdef
			nil,        // lbrace
			nil,        // rbrace
			nil,        // empty
			nil,        // gostring
			nil,        // goint
			nil,        // goint64
			nil,        // gobool
			nil,        // gofloat64
			nil,        // gotag
			nil,        // semicolon
			reduce(19), // plus, reduce: Expression
			reduce(19), // minus, reduce: Expression
			shift(31),  // mul
			shift(32),  // div
			nil,        // lparen
			reduce(19), // rparen, reduce: Expression
			nil,        // int
		},
	},
	actionRow{ // S36
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // cmdcodegengostruct
			nil,        // gotypeof
			nil,        // ident
			nil,        // gostructdef
			nil,        // lbrace
			nil,        // rbrace
			nil,        // empty
			nil,        // gostring
			nil,        // goint
			nil,        // goint64
			nil,        // gobool
			nil,        // gofloat64
			nil,        // gotag
			nil,        // semicolon
			reduce(23), // plus, reduce: Term
			reduce(23), // minus, reduce: Term
			reduce(23), // mul, reduce: Term
			reduce(23), // div, reduce: Term
			nil,        // lparen
			reduce(23), // rparen, reduce: Term
			nil,        // int
		},
	},
	actionRow{ // S37
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // cmdcodegengostruct
			nil,        // gotypeof
			nil,        // ident
			nil,        // gostructdef
			nil,        // lbrace
			nil,        // rbrace
			nil,        // empty
			nil,        // gostring
			nil,        // goint
			nil,        // goint64
			nil,        // gobool
			nil,        // gofloat64
			nil,        // gotag
			nil,        // semicolon
			reduce(24), // plus, reduce: Term
			reduce(24), // minus, reduce: Term
			reduce(24), // mul, reduce: Term
			reduce(24), // div, reduce: Term
			nil,        // lparen
			reduce(24), // rparen, reduce: Term
			nil,        // int
		},
	},
	actionRow{ // S38
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // cmdcodegengostruct
			nil,        // gotypeof
			nil,        // ident
			nil,        // gostructdef
			nil,        // lbrace
			nil,        // rbrace
			nil,        // empty
			nil,        // gostring
			nil,        // goint
			nil,        // goint64
			nil,        // gobool
			nil,        // gofloat64
			nil,        // gotag
			nil,        // semicolon
			reduce(26), // plus, reduce: Factor
			reduce(26), // minus, reduce: Factor
			reduce(26), // mul, reduce: Factor
			reduce(26), // div, reduce: Factor
			nil,        // lparen
			reduce(26), // rparen, reduce: Factor
			nil,        // int
		},
	},
	actionRow{ // S39
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // cmdcodegengostruct
			nil,       // gotypeof
			reduce(7), // ident, reduce: GoStructFields
			nil,       // gostructdef
			nil,       // lbrace
			reduce(7), // rbrace, reduce: GoStructFields
			nil,       // empty
			nil,       // gostring
			nil,       // goint
			nil,       // goint64
			nil,       // gobool
			nil,       // gofloat64
			nil,       // gotag
			nil,       // semicolon
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // div
			nil,       // lparen
			nil,       // rparen
			nil,       // int
		},
	},
	actionRow{ // S40
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // cmdcodegengostruct
			nil,       // gotypeof
			shift(41), // ident
			nil,       // gostructdef
			nil,       // lbrace
			shift(42), // rbrace
			nil,       // empty
			nil,       // gostring
			nil,       // goint
			nil,       // goint64
			nil,       // gobool
			nil,       // gofloat64
			nil,       // gotag
			nil,       // semicolon
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // div
			nil,       // lparen
			nil,       // rparen
			nil,       // int
		},
	},
	actionRow{ // S41
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // cmdcodegengostruct
			nil,       // gotypeof
			nil,       // ident
			nil,       // gostructdef
			nil,       // lbrace
			nil,       // rbrace
			nil,       // empty
			shift(45), // gostring
			shift(46), // goint
			shift(47), // goint64
			shift(48), // gobool
			shift(49), // gofloat64
			nil,       // gotag
			nil,       // semicolon
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // div
			nil,       // lparen
			nil,       // rparen
			nil,       // int
		},
	},
	actionRow{ // S42
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(5), // $, reduce: Param
			nil,       // cmdcodegengostruct
			nil,       // gotypeof
			nil,       // ident
			nil,       // gostructdef
			nil,       // lbrace
			nil,       // rbrace
			nil,       // empty
			nil,       // gostring
			nil,       // goint
			nil,       // goint64
			nil,       // gobool
			nil,       // gofloat64
			nil,       // gotag
			nil,       // semicolon
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // div
			nil,       // lparen
			nil,       // rparen
			nil,       // int
		},
	},
	actionRow{ // S43
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // cmdcodegengostruct
			nil,       // gotypeof
			reduce(6), // ident, reduce: GoStructFields
			nil,       // gostructdef
			nil,       // lbrace
			reduce(6), // rbrace, reduce: GoStructFields
			nil,       // empty
			nil,       // gostring
			nil,       // goint
			nil,       // goint64
			nil,       // gobool
			nil,       // gofloat64
			nil,       // gotag
			nil,       // semicolon
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // div
			nil,       // lparen
			nil,       // rparen
			nil,       // int
		},
	},
	actionRow{ // S44
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // cmdcodegengostruct
			nil,        // gotypeof
			reduce(15), // ident, reduce: GoTag
			nil,        // gostructdef
			nil,        // lbrace
			reduce(15), // rbrace, reduce: GoTag
			nil,        // empty
			nil,        // gostring
			nil,        // goint
			nil,        // goint64
			nil,        // gobool
			nil,        // gofloat64
			shift(51),  // gotag
			nil,        // semicolon
			nil,        // plus
			nil,        // minus
			nil,        // mul
			nil,        // div
			nil,        // lparen
			nil,        // rparen
			nil,        // int
		},
	},
	actionRow{ // S45
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // cmdcodegengostruct
			nil,       // gotypeof
			reduce(9), // ident, reduce: GoType
			nil,       // gostructdef
			nil,       // lbrace
			reduce(9), // rbrace, reduce: GoType
			nil,       // empty
			nil,       // gostring
			nil,       // goint
			nil,       // goint64
			nil,       // gobool
			nil,       // gofloat64
			reduce(9), // gotag, reduce: GoType
			nil,       // semicolon
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // div
			nil,       // lparen
			nil,       // rparen
			nil,       // int
		},
	},
	actionRow{ // S46
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // cmdcodegengostruct
			nil,        // gotypeof
			reduce(10), // ident, reduce: GoType
			nil,        // gostructdef
			nil,        // lbrace
			reduce(10), // rbrace, reduce: GoType
			nil,        // empty
			nil,        // gostring
			nil,        // goint
			nil,        // goint64
			nil,        // gobool
			nil,        // gofloat64
			reduce(10), // gotag, reduce: GoType
			nil,        // semicolon
			nil,        // plus
			nil,        // minus
			nil,        // mul
			nil,        // div
			nil,        // lparen
			nil,        // rparen
			nil,        // int
		},
	},
	actionRow{ // S47
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // cmdcodegengostruct
			nil,        // gotypeof
			reduce(11), // ident, reduce: GoType
			nil,        // gostructdef
			nil,        // lbrace
			reduce(11), // rbrace, reduce: GoType
			nil,        // empty
			nil,        // gostring
			nil,        // goint
			nil,        // goint64
			nil,        // gobool
			nil,        // gofloat64
			reduce(11), // gotag, reduce: GoType
			nil,        // semicolon
			nil,        // plus
			nil,        // minus
			nil,        // mul
			nil,        // div
			nil,        // lparen
			nil,        // rparen
			nil,        // int
		},
	},
	actionRow{ // S48
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // cmdcodegengostruct
			nil,        // gotypeof
			reduce(12), // ident, reduce: GoType
			nil,        // gostructdef
			nil,        // lbrace
			reduce(12), // rbrace, reduce: GoType
			nil,        // empty
			nil,        // gostring
			nil,        // goint
			nil,        // goint64
			nil,        // gobool
			nil,        // gofloat64
			reduce(12), // gotag, reduce: GoType
			nil,        // semicolon
			nil,        // plus
			nil,        // minus
			nil,        // mul
			nil,        // div
			nil,        // lparen
			nil,        // rparen
			nil,        // int
		},
	},
	actionRow{ // S49
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // cmdcodegengostruct
			nil,        // gotypeof
			reduce(13), // ident, reduce: GoType
			nil,        // gostructdef
			nil,        // lbrace
			reduce(13), // rbrace, reduce: GoType
			nil,        // empty
			nil,        // gostring
			nil,        // goint
			nil,        // goint64
			nil,        // gobool
			nil,        // gofloat64
			reduce(13), // gotag, reduce: GoType
			nil,        // semicolon
			nil,        // plus
			nil,        // minus
			nil,        // mul
			nil,        // div
			nil,        // lparen
			nil,        // rparen
			nil,        // int
		},
	},
	actionRow{ // S50
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // cmdcodegengostruct
			nil,       // gotypeof
			reduce(8), // ident, reduce: GoStructField
			nil,       // gostructdef
			nil,       // lbrace
			reduce(8), // rbrace, reduce: GoStructField
			nil,       // empty
			nil,       // gostring
			nil,       // goint
			nil,       // goint64
			nil,       // gobool
			nil,       // gofloat64
			nil,       // gotag
			nil,       // semicolon
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // div
			nil,       // lparen
			nil,       // rparen
			nil,       // int
		},
	},
	actionRow{ // S51
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // cmdcodegengostruct
			nil,        // gotypeof
			reduce(14), // ident, reduce: GoTag
			nil,        // gostructdef
			nil,        // lbrace
			reduce(14), // rbrace, reduce: GoTag
			nil,        // empty
			nil,        // gostring
			nil,        // goint
			nil,        // goint64
			nil,        // gobool
			nil,        // gofloat64
			nil,        // gotag
			nil,        // semicolon
			nil,        // plus
			nil,        // minus
			nil,        // mul
			nil,        // div
			nil,        // lparen
			nil,        // rparen
			nil,        // int
		},
	},
}
