// Code generated by gocc; DO NOT EDIT.

package parser

const numNTSymbols = 8

type (
	gotoTable [numStates]gotoRow
	gotoRow   [numNTSymbols]int
)

var gotoTab = gotoTable{
	gotoRow{ // S0
		-1, // S'
		1,  // Program
		2,  // Statements
		-1, // Statement
		-1, // Expression
		-1, // Operation
		-1, // Term
		-1, // Factor
	},
	gotoRow{ // S1
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // Statement
		-1, // Expression
		-1, // Operation
		-1, // Term
		-1, // Factor
	},
	gotoRow{ // S2
		-1, // S'
		-1, // Program
		-1, // Statements
		3,  // Statement
		4,  // Expression
		-1, // Operation
		5,  // Term
		6,  // Factor
	},
	gotoRow{ // S3
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // Statement
		-1, // Expression
		-1, // Operation
		-1, // Term
		-1, // Factor
	},
	gotoRow{ // S4
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // Statement
		-1, // Expression
		10, // Operation
		-1, // Term
		-1, // Factor
	},
	gotoRow{ // S5
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // Statement
		-1, // Expression
		-1, // Operation
		-1, // Term
		-1, // Factor
	},
	gotoRow{ // S6
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // Statement
		-1, // Expression
		-1, // Operation
		-1, // Term
		-1, // Factor
	},
	gotoRow{ // S7
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // Statement
		15, // Expression
		-1, // Operation
		16, // Term
		17, // Factor
	},
	gotoRow{ // S8
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // Statement
		-1, // Expression
		-1, // Operation
		-1, // Term
		-1, // Factor
	},
	gotoRow{ // S9
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // Statement
		-1, // Expression
		-1, // Operation
		-1, // Term
		-1, // Factor
	},
	gotoRow{ // S10
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // Statement
		-1, // Expression
		-1, // Operation
		20, // Term
		6,  // Factor
	},
	gotoRow{ // S11
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // Statement
		-1, // Expression
		-1, // Operation
		-1, // Term
		-1, // Factor
	},
	gotoRow{ // S12
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // Statement
		-1, // Expression
		-1, // Operation
		-1, // Term
		-1, // Factor
	},
	gotoRow{ // S13
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // Statement
		-1, // Expression
		-1, // Operation
		-1, // Term
		21, // Factor
	},
	gotoRow{ // S14
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // Statement
		-1, // Expression
		-1, // Operation
		-1, // Term
		22, // Factor
	},
	gotoRow{ // S15
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // Statement
		-1, // Expression
		23, // Operation
		-1, // Term
		-1, // Factor
	},
	gotoRow{ // S16
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // Statement
		-1, // Expression
		-1, // Operation
		-1, // Term
		-1, // Factor
	},
	gotoRow{ // S17
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // Statement
		-1, // Expression
		-1, // Operation
		-1, // Term
		-1, // Factor
	},
	gotoRow{ // S18
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // Statement
		27, // Expression
		-1, // Operation
		16, // Term
		17, // Factor
	},
	gotoRow{ // S19
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // Statement
		-1, // Expression
		-1, // Operation
		-1, // Term
		-1, // Factor
	},
	gotoRow{ // S20
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // Statement
		-1, // Expression
		-1, // Operation
		-1, // Term
		-1, // Factor
	},
	gotoRow{ // S21
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // Statement
		-1, // Expression
		-1, // Operation
		-1, // Term
		-1, // Factor
	},
	gotoRow{ // S22
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // Statement
		-1, // Expression
		-1, // Operation
		-1, // Term
		-1, // Factor
	},
	gotoRow{ // S23
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // Statement
		-1, // Expression
		-1, // Operation
		28, // Term
		17, // Factor
	},
	gotoRow{ // S24
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // Statement
		-1, // Expression
		-1, // Operation
		-1, // Term
		-1, // Factor
	},
	gotoRow{ // S25
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // Statement
		-1, // Expression
		-1, // Operation
		-1, // Term
		29, // Factor
	},
	gotoRow{ // S26
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // Statement
		-1, // Expression
		-1, // Operation
		-1, // Term
		30, // Factor
	},
	gotoRow{ // S27
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // Statement
		-1, // Expression
		23, // Operation
		-1, // Term
		-1, // Factor
	},
	gotoRow{ // S28
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // Statement
		-1, // Expression
		-1, // Operation
		-1, // Term
		-1, // Factor
	},
	gotoRow{ // S29
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // Statement
		-1, // Expression
		-1, // Operation
		-1, // Term
		-1, // Factor
	},
	gotoRow{ // S30
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // Statement
		-1, // Expression
		-1, // Operation
		-1, // Term
		-1, // Factor
	},
	gotoRow{ // S31
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // Statement
		-1, // Expression
		-1, // Operation
		-1, // Term
		-1, // Factor
	},
}
