// Code generated by gocc; DO NOT EDIT.

package parser

import (
	"github.com/day-dreams/TrivialCompiler/ast"
)

type (
	//TODO: change type and variable names to be consistent with other tables
	ProdTab      [numProductions]ProdTabEntry
	ProdTabEntry struct {
		String     string
		Id         string
		NTType     int
		Index      int
		NumSymbols int
		ReduceFunc func([]Attrib) (Attrib, error)
	}
	Attrib interface {
	}
)

var productionsTable = ProdTab{
	ProdTabEntry{
		String: `S' : Program	<<  >>`,
		Id:         "S'",
		NTType:     0,
		Index:      0,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Program : Statements	<< ast.NewProgram(X[0]) >>`,
		Id:         "Program",
		NTType:     1,
		Index:      1,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.NewProgram(X[0])
		},
	},
	ProdTabEntry{
		String: `Program : Command	<< ast.NewProgram(X[0]) >>`,
		Id:         "Program",
		NTType:     1,
		Index:      2,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.NewProgram(X[0])
		},
	},
	ProdTabEntry{
		String: `Command : Cmd Param	<< ast.NewCommand(X[0],X[1]) >>`,
		Id:         "Command",
		NTType:     2,
		Index:      3,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.NewCommand(X[0], X[1])
		},
	},
	ProdTabEntry{
		String: `Cmd : cmdcodegengostruct	<< ast.NewCmd(X[0]) >>`,
		Id:         "Cmd",
		NTType:     3,
		Index:      4,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.NewCmd(X[0])
		},
	},
	ProdTabEntry{
		String: `Param : gotypeof ident gostructdef lbrace GoStructFields rbrace	<< ast.NewParam(X[1],X[4]) >>`,
		Id:         "Param",
		NTType:     4,
		Index:      5,
		NumSymbols: 6,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.NewParam(X[1], X[4])
		},
	},
	ProdTabEntry{
		String: `GoStructFields : GoStructFields GoStructField	<< ast.AppendGoStructField(X[0], X[1]) >>`,
		Id:         "GoStructFields",
		NTType:     5,
		Index:      6,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.AppendGoStructField(X[0], X[1])
		},
	},
	ProdTabEntry{
		String: `GoStructFields : empty	<< ast.NewGoStructFieldList() >>`,
		Id:         "GoStructFields",
		NTType:     5,
		Index:      7,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.NewGoStructFieldList()
		},
	},
	ProdTabEntry{
		String: `GoStructField : ident GoType gotag	<< ast.NewGoStructField(X[0],X[1]) >>`,
		Id:         "GoStructField",
		NTType:     6,
		Index:      8,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.NewGoStructField(X[0], X[1])
		},
	},
	ProdTabEntry{
		String: `GoType : gostring	<<  >>`,
		Id:         "GoType",
		NTType:     7,
		Index:      9,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `GoType : goint	<<  >>`,
		Id:         "GoType",
		NTType:     7,
		Index:      10,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `GoType : goint64	<<  >>`,
		Id:         "GoType",
		NTType:     7,
		Index:      11,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `GoType : gobool	<<  >>`,
		Id:         "GoType",
		NTType:     7,
		Index:      12,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `GoType : gofloat64	<<  >>`,
		Id:         "GoType",
		NTType:     7,
		Index:      13,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Statements : Statements Statement	<< ast.AppendStatement(X[0], X[1]) >>`,
		Id:         "Statements",
		NTType:     8,
		Index:      14,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.AppendStatement(X[0], X[1])
		},
	},
	ProdTabEntry{
		String: `Statements : empty	<< ast.NewStatementList() >>`,
		Id:         "Statements",
		NTType:     8,
		Index:      15,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.NewStatementList()
		},
	},
	ProdTabEntry{
		String: `Statement : Expression semicolon	<< ast.NewExpressionStatement(X[0]) >>`,
		Id:         "Statement",
		NTType:     9,
		Index:      16,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.NewExpressionStatement(X[0])
		},
	},
	ProdTabEntry{
		String: `Expression : Expression Operation Term	<< ast.NewInfixExpression(X[0], X[2], X[1]) >>`,
		Id:         "Expression",
		NTType:     10,
		Index:      17,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.NewInfixExpression(X[0], X[2], X[1])
		},
	},
	ProdTabEntry{
		String: `Expression : Term	<<  >>`,
		Id:         "Expression",
		NTType:     10,
		Index:      18,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Operation : plus	<<  >>`,
		Id:         "Operation",
		NTType:     11,
		Index:      19,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Operation : minus	<<  >>`,
		Id:         "Operation",
		NTType:     11,
		Index:      20,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Term : Term mul Factor	<< ast.NewInfixExpression(X[0], X[2], X[1]) >>`,
		Id:         "Term",
		NTType:     12,
		Index:      21,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.NewInfixExpression(X[0], X[2], X[1])
		},
	},
	ProdTabEntry{
		String: `Term : Term div Factor	<< ast.NewInfixExpression(X[0], X[2], X[1]) >>`,
		Id:         "Term",
		NTType:     12,
		Index:      22,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.NewInfixExpression(X[0], X[2], X[1])
		},
	},
	ProdTabEntry{
		String: `Term : Factor	<<  >>`,
		Id:         "Term",
		NTType:     12,
		Index:      23,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Factor : lparen Expression rparen	<< X[1], nil >>`,
		Id:         "Factor",
		NTType:     13,
		Index:      24,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[1], nil
		},
	},
	ProdTabEntry{
		String: `Factor : int	<< ast.NewIntegerLiteral(X[0]) >>`,
		Id:         "Factor",
		NTType:     13,
		Index:      25,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.NewIntegerLiteral(X[0])
		},
	},
}
